export const initialIncidenteVulnerabilidade = {
    numeroChamado: '',
    tarefaRelacionada: '',
    autorId: '',
    atribuidoParaId: '',
    assunto: '',
    tipo: 'Incidente', 
    situacao: 'Aberta', 
    unidadeId: '',
    categoriaId: '',
    ipOrigem: '',
    ipDestino: '',
    nomeHost: '',
    dataCriacao: '', 
    dataAlteracao: '',
    dataConclusao: '',
    tempoEstimado: '',
    natureza: '',
    prioridade: 'Média', 
    cc: [], 
    descricao: '',
    notas: '',
};